### ISSUE TITLE
[JS] onObjectFinalized crash genkit start

### ISSUE THREAD

**Issue by katopz** [firebase/genkit#1123]
**Describe the bug**

onObjectFinalized break `genkit start`

**To Reproduce**
Add this code to `genkit` any example that has `defineFlow` or `onFlow`
```ts
import { onObjectFinalized } from "firebase-functions/v2/storage";

exports.after_upload_pdf = onObjectFinalized({ cpu: 2 }, async (event) => {
  console.log(event);
});
```
then `genkit start` and get
```
Registering flow: fooFlow
 
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
/Users/katopz/git/talent-finder/firebase/functions/node_modules/firebase-functions/lib/v2/providers/storage.js:177
        throw new Error("Missing bucket name. If you are unit testing, please provide a bucket name" +
        ^

Error: Missing bucket name. If you are unit testing, please provide a bucket name by providing bucket name directly in the event handler or by setting process.env.FIREBASE_CONFIG.
    at getOptsAndBucket (/Users/katopz/git/talent-finder/firebase/functions/node_modules/firebase-functions/lib/v2/providers/storage.js:177:15)
    at onOperation (/Users/katopz/git/talent-finder/firebase/functions/node_modules/firebase-functions/lib/v2/providers/storage.js:104:28)
    at onObjectFinalized (/Users/katopz/git/talent-finder/firebase/functions/node_modules/firebase-functions/lib/v2/providers/storage.js:68:12)
    at Object.<anonymous> (/Users/katopz/git/talent-finder/firebase/functions/lib/triggers/uploaded_pdf_to_vector.js:7:60)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
```

**Expected behavior**
No error.

**Screenshots**

**Runtime (please complete the following information):**
 - OS: MacOS
 - Version 14.6.1

** Node version
 -  v22.8.0

**Additional context**
It seem like there are some conflict, everything working fine until i try add some trigger function which i think i didn't initialize firebase admin properly but it turn out just onObjectFinalized is enough to break things.

For workaround maybe I have deploy that trigger function separately but `genkit` will yell at me anyway if i still include this in index file. 🥹

**Comment by katopz** [comment]
Oh! like always, after asking and shower I got my own answer! I've to add `bucket: "YOUR_BUCKET_NAME"` for [StorageOptions](https://github.com/firebase/firebase-functions/blob/6df3787eadbc5d7778644844b0b7e199b15dc807/src/v2/providers/storage.ts#L203)

```ts
import { onObjectFinalized } from "firebase-functions/v2/storage";

exports.after_upload_pdf = onObjectFinalized({ cpu: 2, bucket: "YOUR_BUCKET_NAME" }, async (event) => {
  console.log(event);
});
```

I blame the doc here https://firebase.google.com/docs/functions/gcp-storage-events?gen=2nd#scoping
I have to dig into the code to realized this one.

Thanks
