### ISSUE TITLE
[JS] __genkit__sessionState causes schema validation to fail

### ISSUE THREAD

**Issue by kevinthecheung** [firebase/genkit#1126]
**Describe the bug**
__genkit__sessionState causes schema validation to fail. Error:

```
Error: INVALID_ARGUMENT: Schema validation failed. Parse Errors:

- (root): must NOT have additional properties

Provided data:

{
  "__genkit__sessionState": {},
  "theme": "medieval"
}

Required JSON schema:

{
  "type": "object",
  "properties": {
    "theme": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "additionalProperties": false
}
    at parseSchema (/Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/@genkit-ai+core@0.9.0-dev.2/node_modules/@genkit-ai/core/src/schema.ts:110:21)
    at <anonymous> (/Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/@genkit-ai+core@0.9.0-dev.2/node_modules/@genkit-ai/core/src/action.ts:123:13)
    at Generator.next (<anonymous>)
    at /Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/@genkit-ai+core@0.9.0-dev.2/node_modules/@genkit-ai/core/lib/action.js:36:61
    at new Promise (<anonymous>)
    at __async (/Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/@genkit-ai+core@0.9.0-dev.2/node_modules/@genkit-ai/core/lib/action.js:20:10)
    at actionFn (/Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/@genkit-ai+core@0.9.0-dev.2/node_modules/@genkit-ai/core/src/action.ts:122:40)
    at Genkit.<anonymous> (/Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/genkit@0.9.0-dev.2/node_modules/genkit/src/genkit.ts:477:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevincheung/tmp/0.9-dev.2-test/node_modules/.pnpm/genkit@0.9.0-dev.2/node_modules/genkit/lib/genkit.js:40:24)
```

**To Reproduce**
menu.prompt

```
---
model: googleai/gemini-1.5-flash
input:
  schema:
    theme?: string
  default:
    theme: "pirate"
output:
  schema:
    dishname: string
    description: string
    calories: integer
    allergens(array): string
---
Invent a menu item for a {{theme}} themed restaurant.
```

Code:

```
const menuPrompt = await ai.prompt("menu");
const { data } = await menuPrompt({ theme: "medieval" });
```

**Expected behavior**

**Screenshots**

**Runtime (please complete the following information):**
 - OS: [e.g. Linux, MacOS]

** Node version
 -  run `node --version` at paste here

**Additional context**

**Comment by apascal07** [comment]
@MichaelDoyle Is this related to your change? Or has your change fixed this?

**Comment by MichaelDoyle** [comment]
Thanks for reporting! Fixed by https://github.com/firebase/genkit/pull/1124
