### ISSUE TITLE
[JS] Quota exceeded for `textembedding-gecko`

### ISSUE THREAD

**Issue by katopz** [firebase/genkit#1127]
**Describe the bug**
Quota exceeded for `textembedding-gecko` but the embedder is `vertexai/text-multilingual-embedding-002`

**To Reproduce**
Call many of
```ts
const embedding = await embed({
  embedder: textMultilingualEmbedding002,
  content: text,
});
```

**Expected behavior**
base model should be `vertexai/text-multilingual-embedding-002` not `textembedding-gecko`

**Screenshots**
<img width="632" alt="image" src="https://github.com/user-attachments/assets/baaba89b-2603-4f8b-a94b-0d597d0c8fe2">

**Runtime (please complete the following information):**
 - OS: MacOS
 - Version 14.6.1

** Node version
 -  v22.8.0

**Additional context**
```
Error from Vertex AI predict: HTTP 429: { "error": { "code": 429, "message": "Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: textembedding-gecko. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.", "status": "RESOURCE_EXHAUSTED" } }
Error: Error from Vertex AI predict: HTTP 429: {
  "error": {
    "code": 429,
    "message": "Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: textembedding-gecko. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.",
    "status": "RESOURCE_EXHAUSTED"
  }
}

    at /Users/katopz/git/talent-finder/firebase/functions/node_modules/@genkit-ai/vertexai/lib/predict.js:88:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/katopz/git/talent-finder/firebase/functions/node_modules/@genkit-ai/vertexai/lib/predict.js:33:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

I'm pretty sure that model are correct because i dig in to 
https://github.com/firebase/genkit/blob/98e6a673e352cb45864220e922d13cf6f237a7c9/js/plugins/vertexai/src/predict.ts#L58-L60

and log the model name and it correctly print `model: 'text-multilingual-embedding-002'`.
so this is totally look weird to me because the error shown `textembedding-gecko`.

Maybe any api that return the model info to ensure the correctness? Which should better than get model info randomly from an error.

Thanks

**Comment by katopz** [comment]
To answer my own question, everything seem to be mess up there for version and label

https://github.com/firebase/genkit/blob/bd7aa3de2efa81165e9b69aac993bb250a5ad9d0/js/plugins/googleai/src/embedder.ts#L51-L73

```ts
export const textEmbeddingGecko001 = embedderRef({
  name: 'googleai/embedding-001',
  configSchema: GeminiEmbeddingConfigSchema,
  info: {
    dimensions: 768,
    label: 'Google Gen AI - Text Embedding Gecko (Legacy)',
    supports: {
      input: ['text'],
    },
  },
});

export const textEmbedding004 = embedderRef({
  name: 'googleai/text-embedding-004',
  configSchema: GeminiEmbeddingConfigSchema,
  info: {
    dimensions: 768,
    label: 'Google Gen AI - Text Embedding 001',
    supports: {
      input: ['text'],
    },
  },
});
```

So `googleai/embedding-001'` = `Google Gen AI - Text Embedding Gecko (Legacy)`
And `googleai/text-embedding-004` = `Google Gen AI - Text Embedding 001`

What's going on here 🥲

**Comment by MichaelDoyle** [comment]
Sorry for the confusion with the labels.

Closing as the legacy googleai plugin is deprecated in favor of the google genai plugin.
