### ISSUE TITLE
[JS] [Next] Cannot read properties of undefined (reading 'role')

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#1162]
**Describe the bug**
Error calling to Gemini on `next`.  I confirmed I can call Gemini from the DevUI directly and with other flows, so it's something about this setup.

Maybe a meta-bug that I'm unable to diagnose the error beyond this using the trace, it looks like it's getting something back from Vertex but crashing out parsing it, but there's no logging even at info that shows what the response was.

```
Cannot read properties of undefined (reading 'role')
TypeError: Cannot read properties of undefined (reading 'role')
    at toGeminiMessage (/Users/samphillips/dev/genkit/genkit/samples/js-angular/server/node_modules/@genkit-ai/vertexai/src/gemini.ts:242:32)
    at <anonymous> (/Users/samphillips/dev/genkit/genkit/samples/js-angular/server/node_modules/@genkit-ai/vertexai/src/gemini.ts:507:19)
    at Generator.next (<anonymous>)
    at /Users/samphillips/dev/genkit/genkit/samples/js-angular/server/node_modules/@genkit-ai/vertexai/lib/gemini.js:56:61
    at new Promise (<anonymous>)
    at __async (/Users/samphillips/dev/genkit/genkit/samples/js-angular/server/node_modules/@genkit-ai/vertexai/lib/gemini.js:40:10)
    ```

**To Reproduce**
```
import vertexAI, { gemini15Pro } from '@genkit-ai/vertexai';
import { genkit, MessageSchema, z } from 'genkit';

export const ai = genkit({
  plugins: [vertexAI()],
});

import { logger } from 'genkit/logging';

logger.setLogLevel('debug')

const promptText = `
Hi, I'm jim
 `.trim();

export const ChatRequestSchema = z.object({
  history: z.array(MessageSchema),
  query: z.string(),
}); 

const prompt = ai.definePrompt({
    name: "chatPrompt",
    model: gemini15Pro,
    input: {
        schema: ChatRequestSchema,
    },
    output: {
        schema: z.string(),
    },
}, promptText);

export const chat = ai.defineFlow({
    name: "chat",
    inputSchema: ChatRequestSchema,
    outputSchema: z.string(),
}, async (input): Promise<string> => {
    return (await prompt(input)).output;
});

chat({
  history: [],
  query: 'him, what is great?',
}).then(result => {
  console.log("Got result");
  console.log(result);
});
```

**Expected behavior**
Calls the model successfully.

**Screenshots**
![image](https://github.com/user-attachments/assets/a13aecc2-cdc3-4ecf-b25e-e2fa9c47bb74)

**Runtime (please complete the following information):**
Mac

** Node version
`v20.11.1`

**Additional context**
Synced to `next` at 325c5b7535b36ce7cb42b7fc9f1223dd56e78ed3

**Comment by pavelgj** [comment]
Closing due to inactivity. Reopen if this is still an issue.
