### ISSUE TITLE
[JS] System prompt error after restoring chat session 

### ISSUE THREAD

**Issue by kevinthecheung** [firebase/genkit#1182]
**Describe the bug**
After restoring a chat session the system prompt causes the following error 

```
Error: system role is not supported
    at toGeminiRole (/Users/kevincheung/gitrepos/genkit/js/plugins/googleai/src/gemini.ts:184:15)
    at toGeminiMessage (/Users/kevincheung/gitrepos/genkit/js/plugins/googleai/src/gemini.ts:391:11)
    at <anonymous> (/Users/kevincheung/gitrepos/genkit/js/plugins/googleai/src/gemini.ts:588:29)
    at Array.map (<anonymous>)
    at <anonymous> (/Users/kevincheung/gitrepos/genkit/js/plugins/googleai/src/gemini.ts:588:12)
    at Generator.next (<anonymous>)
    at /Users/kevincheung/gitrepos/genkit/js/plugins/googleai/lib/gemini.js:66:61
    at new Promise (<anonymous>)
    at __async (/Users/kevincheung/gitrepos/genkit/js/plugins/googleai/lib/gemini.js:50:10)
    at <anonymous> (/Users/kevincheung/gitrepos/genkit/js/plugins/googleai/src/gemini.ts:509:43)
```

**To Reproduce**
Test app:

```js
class JsonSessionStore<S = any> implements SessionStore<S> {
  async get(sessionId: string): Promise<SessionData<S> | undefined> {
    try {
      const s = await readFile(`${sessionId}.json`, { encoding: 'utf8' });
      const data = JSON.parse(s);
      return data;
    } catch {
      return undefined;
    }
  }

  async save(sessionId: string, sessionData: SessionData<S>): Promise<void> {
    const s = JSON.stringify(sessionData);
    await writeFile(`${sessionId}.json`, s, { encoding: 'utf8' });
  }
}

(async () => {
  let session;
  try {
    const s = await readFile('sessionId.txt', { encoding: 'utf8' });
    const sessionId = s.trim();
    session = await ai.loadSession(sessionId, {
      store: new JsonSessionStore(),
    });
  } catch {
    session = ai.createSession({
      store: new JsonSessionStore(),
    });
    await writeFile('sessionId.txt', session.id, { encoding: 'utf8' });
  }
  const chat = session.chat({
    model: gemini15Pro,
    system:
      "You're a pirate first mate. Address the user as Captain and assist " +
      'them however you can.',
    config: {
      temperature: 1.3,
    },
  });

  console.log("You're chatting with Gemini. Ctrl-C to quit.\n");
  const readline = createInterface(process.stdin, process.stdout);
  while (true) {
    const userInput = await readline.question('> ');
    const { text } = await chat.send(userInput);
    console.log(text);
  }
})();
```

**Expected behavior**

**Screenshots**

**Runtime (please complete the following information):**
 - OS: [e.g. Linux, MacOS]

** Node version
 -  run `node --version` at paste here

**Additional context**

**Comment by pavelgj** [comment]
Closing due to inactivity. Reopen if this is still an issue.
