### ISSUE TITLE
[JS] [Dotprompt] Dotprompt fails with default inputs

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#1396]
**Describe the bug**
Following the [docs example](https://firebase.google.com/docs/genkit/dotprompt) creates an errror parsing the schema when using a default value.  Using `0.9.4`

myprompt.prompt
```
---
model: googleai/gemini-1.5-flash
config:
  temperature: 0.9
input:
  schema:
    location: string
  default:
    location: a restaurant
---

You are the world's most welcoming AI assistant and are currently working at {{location}}.

Greet a guest{{#if name}} named {{name}}{{/if}}{{#if style}} in the style of {{style}}{{/if}}.
```

```
const myPrompt = ai.prompt('myprompt');

(async () => {
    console.log(((await myPrompt()).output));
})();
```

```
/home/user/mytestapp/node_modules/@genkit-ai/core/src/schema.ts:110
  if (!valid) throw new ValidationError({ data, errors: errors!, schema });
                    ^


ValidationError: INVALID_ARGUMENT: Schema validation failed. Parse Errors:

- (root): must be object

Provided data:

undefined

Required JSON schema:

{
  "type": "object",
  "properties": {
    "location": {
      "type": "string"
    }
  },
  "required": [
    "location"
  ],
  "additionalProperties": false
}
    at parseSchema (/home/user/mytestapp/node_modules/@genkit-ai/core/src/schema.ts:110:21)
    at <anonymous> (/home/user/mytestapp/node_modules/@genkit-ai/core/src/action.ts:168:13)
    at Generator.next (<anonymous>)
    at /home/user/mytestapp/node_modules/@genkit-ai/core/lib/action.js:36:61
    at new Promise (<anonymous>)
    at __async (/home/user/mytestapp/node_modules/@genkit-ai/core/lib/action.js:20:10)
    at Function.actionFn.run (/home/user/mytestapp/node_modules/@genkit-ai/core/src/action.ts:167:43)
    at <anonymous> (/home/user/mytestapp/node_modules/@genkit-ai/core/src/action.ts:154:28)
    at Generator.next (<anonymous>)
    at /home/user/mytestapp/node_modules/@genkit-ai/core/lib/action.js:36:61 {
  status: 'INVALID_ARGUMENT',
  detail: {
    errors: [ { path: '(root)', message: 'must be object' } ],
    schema: {
      type: 'object',
      properties: { location: { type: 'string' } },
      required: [ 'location' ],
      additionalProperties: false
    }
  }
  ```

**Comment by owensengoku** [comment]
HI @i2amsam ,

I encounter the same error today.
After trying, I found maybe following code could work
( You need pass an empty object as argument )
Hope this help
```
const myPrompt = ai.prompt('myprompt');

(async () => {
    console.log(((await myPrompt({})).output));
})();
```

**Comment by GitTom** [comment]
I'm having the same problem, just with a different error message.  Specifying an empty object as argument didn't help.

My dotprompt ...

```
---
model: googleai/gemini-2.0-flash
input:
  schema:
    instructions: string
  default:
    instructions: "Greet the user as Alice22."
---

{{role "system"}}

You are a concise AI assistant.

{{role "user"}}

{{instructions}}

```

An excerpt of the error message ...

```
/Users/tom/dev/genkit-try/node_modules/@genkit-ai/googleai/lib/gemini.js:460
  let sortedParts = message.content;
                            ^
TypeError: Cannot read properties of undefined (reading 'content')
    at toGeminiMessage (.../node_modules/@genkit-ai/googleai/lib/gemini.js:460:29)
```

I'm using Node 23.9 on MacOS.  The same dotprompt works fine if I specify the `instructions` argument in my code.

**Comment by MichaelDoyle** [comment]
I believe this was cleaned up. As of today, the prompt looks like this (and uses picoschema w/ optional args)

```handlebars
---
model: googleai/gemini-2.5-flash
config:
  temperature: 0.9
input:
  schema:
    location: string
    style?: string
    name?: string
  default:
    location: a restaurant
---

You are the world's most welcoming AI assistant and are currently working at {{location}}.

Greet a guest{{#if name}} named {{name}}{{/if}}{{#if style}} in the style of {{style}}{{/if}}.
```
