### ISSUE TITLE
[JS] [Dotprompt] Invalid topK value in docs

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#1397]
**Describe the bug**
Following the docs example [here](https://github.com/firebase/genkit/blob/main/js/doc-snippets/src/dotprompt/prompts/ex03.prompt)

Tested with 0.9.4

```
---
model: googleai/gemini-1.5-flash
config:
  temperature: 1.4
  topK: 50
  topP: 0.4
  maxOutputTokens: 400
  stopSequences:
    -   "<end>"
    -   "<fin>"
---
You are the world's most welcoming AI assistant. Greet the user and offer your assistance.
```
```
const myPrompt = ai.prompt('myprompt');

(async () => {
    console.log(((await myPrompt()).text));
})();
```

```
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [400 Bad Request] Unable to submit request because it has a topK value of 50 but the supported range is from 1 (inclusive) to 41 (exclusive). Update the value and try again.
    at handleResponseNotOk (/home/user/mytestapp/node_modules/@google/generative-ai/dist/index.js:414:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (/home/user/mytestapp/node_modules/@google/generative-ai/dist/index.js:387:9)
    at async generateContent (/home/user/mytestapp/node_modules/@google/generative-ai/dist/index.js:832:22)
    at async ChatSession.sendMessage (/home/user/mytestapp/node_modules/@google/generative-ai/dist/index.js:1146:9) {
  status: 400,
  statusText: 'Bad Request',
  errorDetails: undefined
}
```

**Comment by i2amsam** [comment]
I'm unable to reproduce today, maybe a temporary bug in the Gemini API?  Closing for now since it doesn't reproduce.
