### ISSUE TITLE
[Docs] Rag docs missing `model` to be able to run

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#1406]
Following the Rag docs [here](https://firebase.google.com/docs/genkit/rag) 

```
export const menuQAFlow = ai.defineFlow(
  { name: 'menuQA', inputSchema: z.string(), outputSchema: z.string() },
  async (input: string) => {
    // retrieve relevant documents
    const docs = await ai.retrieve({
      retriever: menuRetriever,
      query: input,
      options: { k: 3 },
    });

    // generate a response
   const { text } = await ai.generate({
      prompt: `
You are acting as a helpful AI assistant that can answer 
questions about the food available on the menu at Genkit Grub Pub.

Use only the context provided to answer the question.
If you don't know, do not make up an answer.
Do not add or change items on the menu.

Question: ${input}`,
      docs,
    });

    return text;
  }
);
```

```
Error: INVALID_ARGUMENT: Must supply a `model` to `generate()` calls.
    at <anonymous> (/home/user/mytestapp/node_modules/@genkit-ai/ai/src/model.ts:503:11)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/mytestapp/node_modules/@genkit-ai/ai/lib/model.js:40:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```
 
We should supple the model in the `genkit` block at the beginning, or in the`ai.generate` call below

**Comment by MichaelDoyle** [comment]
I checked and the docs look up-to-date now.
