### ISSUE TITLE
[Go] http: panic serving [::1]:37832: runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by 231tr0n** [firebase/genkit#1450]
**Describe the bug**
Running the code given in steps to reproduce section will throw this error when hitting endpoint for adding document handler to local vector store.
```
http: panic serving [::1]:55014: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1947 +0xbe
panic({0x8ef6c0?, 0xd6a080?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
	/home/zeltron/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.26.0/trace/span.go:381 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000002180, {0x0, 0x0, 0xc000002180?})
	/home/zeltron/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.26.0/trace/span.go:413 +0x9dc
panic({0x8ef6c0?, 0xd6a080?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/firebase/genkit/go/plugins/localvec.(*docStore).index(0xc00009aa00, {0xa43388, 0xc00015cb10}, 0xc00015ca80)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/plugins/localvec/localvec.go:136 +0xa9
github.com/firebase/genkit/go/ai.DefineIndexer.func1({0xa43388?, 0xc00015cb10?}, 0x7?)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/ai/retriever.go:72 +0x22
github.com/firebase/genkit/go/core.DefineAction[...].func1(0x9779c1?, 0x7?)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/core/action.go:76 +0x22
github.com/firebase/genkit/go/core.newAction[...].func1(0xc00015ca80, 0x0)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/core/action.go:150 +0x64
github.com/firebase/genkit/go/core.(*Action[...]).Run.func3(0xc00015ca80)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/core/action.go:189 +0xfa
github.com/firebase/genkit/go/core/tracing.RunInNewSpan[...]({0xa43350, 0xd9f640}, 0xc000012120, {0xc000028450, 0x17}, {0x977567, 0x6}, 0x0, 0xc00015ca80, 0xc0000df8f0)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/core/tracing/tracing.go:117 +0x4fe
github.com/firebase/genkit/go/core.(*Action[...]).Run(0xa497c0, {0xa43350, 0xd9f640}, 0xc00015ca80, 0x0)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/core/action.go:180 +0x309
github.com/firebase/genkit/go/ai.(*indexerActionDef).Index(0xc00007d9e0?, {0xa43350?, 0xd9f640?}, 0x8?)
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/ai/retriever.go:110 +0x35
github.com/firebase/genkit/go/ai.Index({0xa43350, 0xd9f640}, {0xa413d0, 0xc00009c780}, {0xc0000dfab8, 0x1, 0x10?})
	/home/zeltron/go/pkg/mod/github.com/firebase/genkit/go@v0.2.1/ai/retriever.go:189 +0x97
main.addDocumentHandler({0xa42a10, 0xc0000f80e0}, 0xc0000d8f00)
	/home/zeltron/test/main.go:63 +0x30d
net/http.HandlerFunc.ServeHTTP(0xd7e360?, {0xa42a10?, 0xc0000f80e0?}, 0x2?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x412225?, {0xa42a10, 0xc0000f80e0}, 0xc0000d8f00)
	/usr/local/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xa40bf8?}, {0xa42a10?, 0xc0000f80e0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0000c45a0, {0xa43388, 0xc00015c720})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3360 +0x485
```

**To Reproduce**
```go
package main

import (
	"context"
	"encoding/json"
	"log"
	"net/http"
	_ "net/http/pprof"

	"github.com/firebase/genkit/go/ai"
	"github.com/firebase/genkit/go/plugins/localvec"
	"github.com/firebase/genkit/go/plugins/ollama"
)

// Collection of documents
type addDocumentRequest struct {
	Document string
}

// indexer is local vector store indexer
var indexer ai.Indexer

func init() {
	var err error

	// Initalize ollama package with server address
	err = ollama.Init(context.Background(), &ollama.Config{
		ServerAddress: "http://localhost:11434",
	})
	if err != nil {
		log.Fatalln(err)
	}

	// Initialize localvec package
	if err := localvec.Init(); err != nil {
		log.Fatal(err)
	}

	// Get embeddings of the llm client
	emb := ollama.Embedder("http://localhost:11434")

	// Create new local vector store with embeddings
	indexer, _, err = localvec.DefineIndexerAndRetriever("doc", localvec.Config{Dir: "temp", Embedder: emb})
	if err != nil {
		log.Fatalln(err)
	}
}

// addDocumentHandler is used to store information provided to the vector store
func addDocumentHandler(w http.ResponseWriter, req *http.Request) {
	addDocReq := &addDocumentRequest{}

	// Decode request body
	dec := json.NewDecoder(req.Body)
	dec.DisallowUnknownFields()
	err := dec.Decode(addDocReq)
	if err != nil {
		http.Error(w, "Wrong json format for document addition request", http.StatusBadRequest)
		log.Println(err)
		return
	}

	err = ai.Index(context.Background(), indexer, ai.WithIndexerDocs(ai.DocumentFromText(addDocReq.Document, nil)))
	if err != nil {
		http.Error(w, "Error adding documents to vector store", http.StatusInternalServerError)
		log.Println(err)
		return
	}
}

func main() {
	http.HandleFunc("POST /add", addDocumentHandler)

	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatalln(err)
	}
}
```
1. Initialize this as a go module main package file by doing ``go mod init trial`` and then ``go mod tidy`` in a new directory.
2. Run the file with ``go run .``.
3. Hit the http server endpoint for adding document handler using the following curl command 
```bash
curl -H 'Content-Type: application/json' \
           -d '{"document": "Bob is an idiot."}' \
           -X POST \
           http://localhost:8080/add
```

**Expected behavior**
The document or the string provided should be stored in the localvector store.

**Screenshots**
N/A

**Runtime (please complete the following information):**
 - WSL2
 - WSL version: 2.3.26.0
 - Kernel version: 5.15.167.4-1
 - WSLg version: 1.0.65
 - MSRDC version: 1.2.5620
 - Direct3D version: 1.611.1-81528511
 - DXCore version: 10.0.26100.1-240331-1435.ge-release
 - Windows version: 10.0.22631.4541

**Go version**
 -  go version go1.23.3 linux/amd64

**Additional context**
None

**Comment by tnv01** [comment]
I think the main issue here is that this line:

```
// Get embeddings of the llm client
emb := ollama.Embedder("http://localhost:11434")
```
Returns a nil embedding. According to docs on the `Embedder` function this should be checked for nil before passing it to the `DefineIndexerAndRetriever` function.

However, I think it might also be good for the Indexer to do some error checking for `nil` values of the `Embedder`. I will check with @apascal07 on whether it makes sense for us to do this check (or if will cause more breakages) and then send a fix :)

**Comment by 231tr0n** [comment]
> I think the main issue here is that this line:
> 
> ```
> // Get embeddings of the llm client
> emb := ollama.Embedder("http://localhost:11434")
> ```
> 
> Returns a nil embedding. According to docs on the `Embedder` function this should be checked for nil before passing it to the `DefineIndexerAndRetriever` function.
> 
> However, I think it might also be good for the Indexer to do some error checking for `nil` values of the `Embedder`. I will check with @apascal07 on whether it makes sense for us to do this check (or if will cause more breakages) and then send a fix :)

@tnv01, just a small doubt. Why is this ``ollama.Embedder("http://localhost:11434")`` returning nil here. Is the way I am using it wrong?

**Comment by tnv01** [comment]
I believe you just need to define the ollama model as mentioned here: https://firebase.google.com/docs/genkit-go/plugins/ollama

**Comment by 231tr0n** [comment]
> I believe you just need to define the ollama model as mentioned here: https://firebase.google.com/docs/genkit-go/plugins/ollama

```go
package main

import (
	"context"
	"log/slog"
	"os"

	"github.com/firebase/genkit/go/ai"
	"github.com/firebase/genkit/go/plugins/ollama"
)

func main() {
	err := ollama.Init(context.Background(), &ollama.Config{
		ServerAddress: "http://localhost:11434",
	})
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}

	// Declare new ollama llm client
	_ = ollama.DefineModel(ollama.ModelDefinition{
		Name: "llama3.2:1b",
		Type: "chat",
	},
		&ai.ModelCapabilities{
			Multiturn:  true,
			SystemRole: true,
			Tools:      false,
			Media:      false,
		},
	)

	emb := ollama.Embedder("http://localhost:11434")
	if emb == nil {
		slog.Error("Could not retrieve embeddings")
		os.Exit(1)
	}
}
```
@tnv01, this code snippet does work according to what the docs suggest. As told I have defined a model as well.
