### ISSUE TITLE
[Tooling] Unable to get sample started or connect to firebase emulators

### ISSUE THREAD

**Issue by Flucadetena** [firebase/genkit#1510]
**Describe the bug**
I can neither get the basic flow working after running `firebase init genkit` nor I can get it to work in a Firebase functions repo alongside the emulators.

I know this may be two separated issue, but I think they may be the same bug that is causing the problem.

**To Reproduce**
1. Run `firebase init genkit`
2. Say yes to everything including the sample flow
3. Use VertexAI option
4. Run `genkit start` or `cd functions -- npm run genkit:start`

In this case the error is:
![Captura de pantalla 2024-12-12 a las 22 59 38](https://github.com/user-attachments/assets/7bab2790-160d-45c1-8b56-ede99316be19)

And I'm stuck in this screen of the UI:
![Captura de pantalla 2024-12-12 a las 22 58 35](https://github.com/user-attachments/assets/85dd99cf-8f7d-463c-bbd6-cd8e2c572baa)

**In case of the emulators:**
1. I run `firebase emulators:start --inspect-functions`
2. See both my functions and the flow urls appear in the console
3. Then in the functions repo I run `cd functions -- GENKIT_ENV=dev  npm run genkit:start`

And I see this error if I watch the sample flow file directly, like it is setup by default after init:

```
throw new Error(exports.GoogleAuthExceptionMessages.NO_PROJECT_ID_FOUND);
                  ^

Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at GoogleAuth.findAndCacheProjectId
```

so when calling: `genkit start -- tsx --watch src/genkit-sample.ts`

If I change it to point to the `index.ts` with some other normal firebase functions, I get this error:

```
throw new error_1.FirebaseAppError(error_1.AppErrorCodes.NO_APP, errorMessage);
                  ^

FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
```

And yes the `initializeApp()` is the first thing:
![Captura de pantalla 2024-12-12 a las 23 04 18](https://github.com/user-attachments/assets/9e118a41-1ab7-4f03-bb07-89a9d3f285b9)

In the emulators test I also can't find a way of seeing the Genkit UI, as it show to be in the same place as the emulators ui.
`Genkit Developer UI: http://localhost:4001`

*Since the `-attach` flag has been removed, not sure how can I see both.

**Expected behavior**
- In the basic Genkit test with no emulators I expect to see the GenkitUI
- In the test with the emulators I expect for no errors and to have a way of seeing the emulator ui of Genkit

**Desktop (please complete the following information):**
 - OS: Mac - M1 max - 15.1.1
 - Browser chrome - 31.0.6778.139
 - genkit: 0.9.12

**Comment by anguillanneuf** [comment]
I had trouble with the official Firebase Genkit docs but https://bit.ly/genkit-0-9 is helping me get going so far. The docs seem to have outdated info.

**Comment by Flucadetena** [comment]
Hi @anguillanneuf thanks for the quick response, although my solution is not here. Using genkit with firebase functions already sets the "projectId" and all the credentials that genkit needs, no I should have no problem running the basic sample. 

Sadly this is not the case. Also I need to know how to run the emulators along side the genkit ui to develop correctly.

I'll keep trying things in the meanwhile, but thanks a lot for the help.

**Comment by Flucadetena** [comment]
Ok I found out that running `tsx --watch src/index` when the file has:
```
import * as admin from "firebase-admin";

admin.initializeApp();
```

will through the error that the default app is not initialize.

full error:

```
functions/functions/node_modules/firebase-admin/lib/app/lifecycle.js:65
            throw new error_1.FirebaseAppError(error_1.AppErrorCodes.NO_APP, errorMessage);
                  ^

FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
    at AppStore.getApp (/Users/fer/Desktop/projects/roots/functions/functions/node_modules/firebase-admin/lib/app/lifecycle.js:65:19)
    at getApp (/Users/fer/Desktop/projects/roots/functions/functions/node_modules/firebase-admin/lib/app/lifecycle.js:106:36)
    at getFirestore (/Users/fer/Desktop/projects/roots/functions/functions/node_modules/firebase-admin/lib/firestore/index.js:50:90)
    at <anonymous> (/Users/fer/Desktop/projects/roots/functions/functions/src/services/references.ts:3:13)
    at Object.<anonymous> (/Users/fer/Desktop/projects/roots/functions/functions/src/services/references.ts:28:33)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.transformer (/Users/fer/Desktop/projects/roots/functions/functions/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  errorInfo: {
    code: 'app/no-app',
    message: 'The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.'
  },
  codePrefix: 'app'
}
```

**Comment by Flucadetena** [comment]
Ok I was able to solve the problem and get everything working by:

1.- runing `genkit start` or `npm run genkit:start` only in the file of the sample, so the file that only imports the genkit library and not the firebase admin one.

1.2- Also I had to add the `projectId` param inside the VertexAI plugin as it was not getting it automatically from the env variable although it was correctly set. So:

```
const ai = genkit({
  plugins: [
    // Load the Vertex AI plugin. You can optionally specify your project ID
    // by passing in a config object; if you don't, the Vertex AI plugin uses
    // the value from the GCLOUD_PROJECT environment variable.
    vertexAI({ location: "us-central1", 
        projectId: "YOUR-PROJECT-ID",
     })
  ]
});
```

To run the emulators and get the url to call your functions and genkit flows:
1.- Run `npm run build:watch` to listen to changes in your `index.ts` to rebuild your functions on changes.
2.- In the `index.ts` export you genkit functions as well, so they appear in the emulators logs
```
import * as admin from "firebase-admin";

admin.initializeApp();

import { setGlobalOptions } from "firebase-functions/options";
setGlobalOptions({ region: "us-central1" });

import * as books from "./books/book";
import * as genkitSample from "./genkit-sample";

exports.books = books;
exports.genkitSample = genkitSample;
```
3.- In the emulators configuration make sure to specify the port of the emulators ui to be the `4001`, letting free the port `4000` that the genkit UI uses.
```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "source": "../functions/functions"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8080
    },
    "storage": {
      "port": 9199
    },
    "functions": {
      "port": 5001
    },
    "ui": {
      "enabled": true,
      "port": 4001
    },
    "singleProjectMode": true
  }
}
```
3.- Start the emulators of firebase as normal `firebase emulators:start`

Now you are listen to changes in both genkit and functions, running both emulators and can see both UIs

**Comment by Flucadetena** [comment]
Although the main issue stands, that the VertexAI plugin does not import the project Id from the env variable.

**Comment by MichaelDoyle** [comment]
> Although the main issue stands, that the VertexAI plugin does not import the project Id from the env variable.

Can you clarify which env variable you are referring to here?

Either way, I think you are correct. The Vertex AI plugin is not integrated well with Firebase; it needs to be authenticated separately. These are the steps:

https://firebase.google.com/docs/genkit/plugins/vertex-ai#configuration

I'll open a discussion on discord and we can see what can be done here.
