### ISSUE TITLE
[JS] 

### ISSUE THREAD

**Issue by estherwasatester** [firebase/genkit#833]
**Describe the bug**
Cloud Logging has a limit to the Log Entry. When using Logging with Genkit, it crashes the server if the payload is too large to be logged out and isn't handled gracefully.

**To Reproduce**
When calling a flow with a large payload of 1173202 bytes, if an error occurs in flow, logging fails and crashes the Genkit service as it tries to write out the entire payload.

Error:
```
Error: 3 INVALID_ARGUMENT: Log entry with size 754.2K exceeds maximum size of 256.0K
    at callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:193:76)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Expected behavior**
Handle the error? Not crash the service.

**Runtime (please complete the following information):**
 - Linux

** Node version
v20.16.0

**Additional context**
[Quotas defined at](https://cloud.google.com/logging/quotas)

**Comment by MichaelDoyle** [comment]
Thanks for reporting. We'll get this resolved.

**Comment by pavelgj** [comment]
**This is an automated message.** Closing the issue due to inactivity. Feel free to reopen if still relevant.
