### ISSUE TITLE
[JS] [dotprompt] Must supply a `contentType` when sending File URIs to Gemini.

### ISSUE THREAD

**Issue by odbol** [firebase/genkit#846]
**Describe the bug**

Using the example in the docs for multimodal, I get this error:

```
Must supply a `contentType` when sending File URIs to Gemini.
Error: Must supply a `contentType` when sending File URIs to Gemini.
    at toFileData (/home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:255:11)
    at toGeminiPart (/home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:369:12)
    at Array.map (<anonymous>)
    at toGeminiMessage (/home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:400:28)
    at /home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:532:19
    at Generator.next (<anonymous>)
    at /home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:66:61
    at new Promise (<anonymous>)
    at __async (/home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:50:10)
    at /home/user/gemineye-server/node_modules/@genkit-ai/googleai/lib/gemini.js:479:37
```

**To Reproduce**
```
---
model: googleai/gemini-1.5-pro-latest
config:
  temperature: 0.85
input:
  schema:
    imageUrl: string
---
{{role "system"}}
You are a helpful screen reader assistant for blind people.
{{role "user"}}
Describe the image

{{media url=photoUrl}}
```

**Expected behavior**
Should send the image. Or docs should mention that you need to specify the contentType... somehow (although isn't that supposed to be in the data uri?)

**Screenshots**

**Runtime (please complete the following information):**
 - OS: Linux

** Node version
 -  run `node --version` at paste here
20

**Additional context**

**Comment by danwritecode** [comment]
+1 on this, same error. The example in the docs does not work.

**Comment by moekhalil** [comment]
I used Firebase Studio to create an app with a prompt and _**even that**_ application gets this error thrown.

**Comment by cabljac** [comment]
That error string no longer exists anywhere. It lived in `@genkit-ai/googleai`, which was removed wholesale in ab8718ae4; the plugin directory is gone.

The replacement is tolerant instead of throwing: `js/plugins/google-genai/src/common/converters.ts:126-129` omits `mimeType` entirely when no `contentType` is supplied for a File URI, and lets the Files API infer it. Data URLs still derive the type from the URL itself.

Closing as completed as part of a pass over older issues. If you still hit this on `@genkit-ai/google-genai`, I'll happily reopen this or open a fresh one.
