### ISSUE TITLE
[Google AI plugin] Add support for Gemini experimental models?

### ISSUE THREAD

**Issue by thatfiredev** [firebase/genkit#852]
In August 2024, Gemini launched a few [experimental models](https://ai.google.dev/gemini-api/docs/models/experimental-models). As described in the docs:

> In addition to the [base models](https://ai.google.dev/gemini), the Gemini API offers experimental models available in Preview, as defined in the [Terms](https://ai.google.dev/gemini-api/terms), meaning it is not for production use. We release experimental models to gather feedback, get our latest updates into the hands of developers quickly, and highlight the pace of innovation happening at Google. What we learn from experimental launches informs how we release models more widely. An experimental model can be swapped for another without prior notice. We don't guarantee that an experimental model will become a stable model in the future.

At the time of writing, there are 4 available models:
- gemini-1.5-pro-exp-0801
- gemini-1.5-pro-exp-0827
- gemini-1.5-flash-exp-0827
- gemini-1.5-flash-8b-exp-0827

**Question:** Is this something we would like to support in the Google AI plugin? 
I suspect those may be hard to maintain given that they may change without prior notice. But since Genkit supports marking a model as [unstable](https://github.com/firebase/genkit/blob/adc8ad81759f49b2791a3a87f7fa2a38d137db24/js/ai/src/model.ts#L152), perhaps we could mark those as unstable so that developers don't mistakenly use them in production.

**Comment by MichaelDoyle** [comment]
These are available without any code changes. Maybe we need to improve docs on this? For example:

```typescript
import { configureGenkit } from "@genkit-ai/core";
import { z } from "@genkit-ai/core/schema";
import { generate } from "@genkit-ai/ai";
import { googleAI, gemini15Flash } from "@genkit-ai/googleai";

configureGenkit({
  // set GOOGLE_GENAI_API_KEY env variable to your api key
  plugins: [googleAI()]
});

await generate({
  prompt: "Write a Node.js script to invert a binary tree.",
  model: gemini15Flash,
  config: { version: "gemini-1.5-flash-exp-0827" },
});
```

**Comment by thatfiredev** [comment]
@MichaelDoyle Oh, for some reason I thought we were limited to the [versions specified in the `modelRef`](https://github.com/firebase/genkit/blob/97b722362d6301e4c0becf9ad90c5832f28f6955/js/plugins/googleai/src/gemini.ts#L141). Good to know we can specify any version 👍 

Yes, I think having docs around this would be nice.

**Comment by footballqq** [comment]
i need to use genimi-2.0-flash-lite, where can i check how to write? always get

 GenkitError: NOT_FOUND: Model 'googleai/gemini-2.0-flash-lite' not found
    at <anonymous> (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__827d160c._.js?4:343:24)
    at resolveErrorDev (https://6000-idx-studio-1744616388802.cluster-2xfkbshw5rfguuk5qupw267afs.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17512:48)
    at processFullStringRow (https://6000-idx-studio-1744616388802.cluster-2xfkbshw5rfguuk5qupw267afs.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17728:23)
    at processFullBinaryRow (https://6000-idx-studio-1744616388802.cluster-2xfkbshw5rfguuk5qupw267afs.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17716:9)
    at progress (https://6000-idx-studio-1744616388802.cluster-2xfkbshw5rfguuk5qupw267afs.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17862:102)

**Comment by thatfiredev** [comment]
Closing now that the code example in the docs use the model name (eg. `'gemini-2.5-flash'`): https://genkit.dev/docs/get-started/#create-your-first-application
