### ISSUE TITLE
[JS] Actions page fails to load without gcloud auth

### ISSUE THREAD

**Issue by ssbushi** [firebase/genkit#873]
**Describe the bug**
Actions page does no load, without gcloud auth credentials.

Error in the reflection API:
```

Error: 2 UNKNOWN: Getting metadata from plugin failed with error: {"error":"invalid_grant","error_description":"reauth related error (invalid_rapt)","error_uri":"https://support.google.com/a/answer/9368756","error_subtype":"invalid_rapt"}
    at callErrorFromStatus (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.<anonymous> (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@grpc+grpc-js@1.10.4/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@google-cloud+logging@11.0.0_encoding@0.1.13/node_modules/@google-cloud/logging/build/src/v2/logging_service_v2_client.js:253:29
    at /usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/google-gax@4.3.2_encoding@0.1.13/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/google-gax@4.3.2_encoding@0.1.13/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at Task._apiCall (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/google-gax@4.3.2_encoding@0.1.13/node_modules/google-gax/build/src/normalCalls/retries.js:119:13)
    at Task.run (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/google-gax@4.3.2_encoding@0.1.13/node_modules/google-gax/build/src/bundlingCalls/task.js:142:35)
    at BundleExecutor._runNow (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/google-gax@4.3.2_encoding@0.1.13/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:189:14)
    at Timeout._onTimeout (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/google-gax@4.3.2_encoding@0.1.13/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:135:22)
    at listOnTimeout (node:internal/timers:573:17)
Emitted 'error' event on DerivedLogger instance at:
    at DerivedLogger.transportEvent (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/winston@3.13.0/node_modules/winston/lib/winston/logger.js:639:12)
    at LoggingWinston.emit (node:events:530:35)
    at errorOrDestroy (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/internal/streams/destroy.js:90:101)
    at onwriteError (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:409:5)
    at onwrite (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:427:11)
    at WritableState.onwrite (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/readable-stream@3.6.2/node_modules/readable-stream/lib/_stream_writable.js:160:5)
    at newCallback (/usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@google-cloud+logging-winston@6.0.0_encoding@0.1.13_winston@3.13.0/node_modules/@google-cloud/logging-winston/build/src/common.js:228:21)
    at /usr/local/google/home/ssbushi/OpenSource/genkit/js/node_modules/.pnpm/@google-cloud+promisify@4.0.0/node_modules/@google-cloud/promisify/build/src/index.js:114:21 {
  code: 2,
  details: 'Getting metadata from plugin failed with error: {"error":"invalid_grant","error_description":"reauth related error (invalid_rapt)","error_uri":"https://support.google.com/a/answer/9368756","error_subtype":"invalid_rapt"}',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```
**To Reproduce**
- `git checkout next`
- `cd js/testapps/cat-evals`
- `genkit start -x`, and have the Dev UI running in `dev` mode (`cd genkit-ui/ && git checkout next && pnpm run build && pnpm run start`)
- Go the the Run tab, to reproduce the error. (You should not have gcloud auth credentials available to reproduce, i.e. you should not have run `gcloud auth ...` recently. `gcloud auth revoke` may help to reset auth credentials.)

**Expected behavior**
Actions load

**Screenshots**
Error in the Dev UI: 
![image](https://github.com/user-attachments/assets/1c3ac148-c2aa-4eb4-b432-6c72d9a4abbb)

**Runtime (please complete the following information):**
 - OS: Linux
 - 6.9.10-1rodete4-amd64

**Node version**
 - v20.11.1

**Additional context**
The error can be mitigated by removing the `telemetry` config in `configureGenkit` under `cat-eval/src/index.ts`.

**Comment by ssbushi** [comment]
Obsolete
